### ISSUE TITLE
未找到与 qiniu Controller 对应的 qiniu Model

### ISSUE THREAD

**Issue by yumengzhong** [hyiron/elapse#17]
你好启动server端回报 ‘未找到与 qiniu Controller 对应的 qiniu Model’ 的错误，我自己添加了一个空的qiuniu  Model，但是我不知道原来项目中进行了什么样的操作，这正是我需要学习的，希望前辈关注解决下

谢谢

**Comment by hyiron** [comment]
@yumengzhong 你好，感谢关注。在``中有这样一段代码：

```javascript
Object.keys(app.controller).forEach(key => {
    if (!app.model[key]) {
      console.info(`未找到与 ${key} Controller 对应的 ${key} Model`)
    } else {
      const modelUrl = `/${key}`;
      const itemUrl = `/${key}/:id`;
      const controller = app.controller[key];
     
      // 以下为配置通用的路由
      controller.findAll && router.get(modelUrl, controller.findAll);
      controller.create && router.post(modelUrl, controller.create);
      controller.findById && router.get(itemUrl, controller.findById);
      controller.deleteById && router.delete(itemUrl, controller.deleteById);
      controller.replaceById && router.put(itemUrl, controller.replaceById);
      controller.updateById && router.patch(itemUrl, controller.updateById);
    }
  })
```

上面的代码通过遍历所有的  `app.controller`  来配置通用的 `路由`。在本项目中我的想法是为配置了`model`的数据模型生成通用的路由配置，故判断`controller` 是否有相应的 `model`，有则配置，没有则不配置，控制台打印出的信息不妨碍项目的运行。

**Comment by yumengzhong** [comment]
@hyiron 你好我注意到这段代码了，我以为是这报错，看了你的解释可能不是这里引发的问题。

在elapse/server/connection/mongodb.js里

```
  db.on('error', () => {
    console.log('数据库连接错误：', err);
    mongoose.disconnect();
  });
```
作者代码忘了 传递 `err`，我在自己本地补充了`(err) => {`之后还是报错，是不是要在我本地进行一些设置

```
数据库连接错误： { MongoError: Authentication failed.
    at /Users/ymz/Documents/project/web/ymz-blog/elapse/server/node_modules/mongodb-core/lib/connection/pool.js:593:63
    at authenticateStragglers (/Users/ymz/Documents/project/web/ymz-blog/elapse/server/node_modules/mongodb-core/lib/connection/pool.js:516:16)
    at Connection.messageHandler (/Users/ymz/Documents/project/web/ymz-blog/elapse/server/node_modules/mongodb-core/lib/connection/pool.js:552:5)
    at emitMessageHandler (/Users/ymz/Documents/project/web/ymz-blog/elapse/server/node_modules/mongodb-core/lib/connection/connection.js:309:10)
    at Socket.<anonymous> (/Users/ymz/Documents/project/web/ymz-blog/elapse/server/node_modules/mongodb-core/lib/connection/connection.js:452:17)
    at emitOne (events.js:116:13)

    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'MongoError',
  message: 'Authentication failed.',
  ok: 0,
  errmsg: 'Authentication failed.',
  code: 18,
  codeName: 'AuthenticationFailed' }
(node:85598) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: Authentication failed.
(node:85598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will termin
ate the Node.js process with a non-zero exit code.
```

**Comment by yumengzhong** [comment]
@hyiron 经过您的提醒，我注意到这段代码，修改了对应代码
```
  if (!config.user || !config.pwd) {
    url = `mongodb://${config.host}:${config.port}/${config.name}`
  } else {
    url = `mongodb://${config.user}:${config.pwd}@${config.host}:${config.port}/${config.name}`
  }
```
现在不报错了，
自己在数据库创建了一个登录账号和密码，我想应该是这样的
现在可以愉快地玩耍了，谢谢作者的项目，我可以学到很多

**Comment by hyiron** [comment]
you are welcomr
